onboarding = false

[keys]
prefix = "ctrl+space"
navigate_workspace_down = "j"
navigate_workspace_up = "k"
navigate_pane_down = "ctrl+j"
navigate_pane_up = "ctrl+k"
remove_worktree = "prefix+shift+k"
next_agent = "prefix+a"
previous_agent = "prefix+shift+a"
